services:  
  mfp:
    build: https://github.com/mhdzumair/mediaflow-proxy.git#main
    container_name: mfp
    restart: unless-stopped
    ports:
      - '8888:8888'
    environment:
      API_PASSWORD: Bizet4cindy
      FORWARDED_ALLOW_IPS: "*"
      TRANSPORT_ROUTES: {"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}
